%YAML 1.2
---
# 代理
PROXY_URL: http://127.0.0.1:7890
REQUEST_KWARGS: { proxy_url: http://127.0.0.1:7890 }

# 机器人命令
MY_COMMANDS_1:
  - [/start, 开始使用]
  - [/hello, 向你问好]
  - [/bing_image, 获取必应今日高清壁纸]
  - [/fund, 获取基金相关信息]
  - [/settings, 设置]
  - [/cancel, 取消操作]
  - [/help, 获取帮助]
MY_COMMANDS_2:
  - [/start, 开始使用]
  - [/hello, 向你问好]
  - [/bing_image, 获取必应今日高清壁纸]
  - [/cancel, 取消操作]
  - [/help, 获取帮助]

# GitHub 文件 Raw 访问路径
GitHub_MyFund: https://raw.githubusercontent.com/KiyanYang/data/main/my-fund.json
jsdelivr:
  fund: https://cdn.jsdelivr.net/gh/KiyanYang/data@main/my-fund.json

# API 访问路径
API_holiday: "https://service-cu3bic1s-1302072848.sg.apigw.tencentcs.com/release/holiday/"
